### ISSUE TITLE
size mismatch for encoder.contextBlock.conv_A1.weight

### ISSUE THREAD

**Issue by carrolltm** [PRBonn/contrastive_association#1]
when i run the code:
python evaluate_4dpanoptic.py --ckpt_ps  pre_trained/panoptic_pq_564.pth --ckpt_ag pre_trained/aggregation_aq_724.ckpt
I face this problem：
  File "save_panoptic_features.py", line 46, in <module>
    main()
  File "/home/wxiao/anaconda3/envs/strack/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/wxiao/anaconda3/envs/strack/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/wxiao/anaconda3/envs/strack/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wxiao/anaconda3/envs/strack/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "save_panoptic_features.py", line 33, in main
    model.load_state_dict(checkpoint['state_dict'])
  File "/home/wxiao/anaconda3/envs/strack/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PanopticCylinder:
        size mismatch for encoder.contextBlock.conv_A1.weight: copying a param with shape torch.Size([3, 1, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 1, 3, 16]).
        size mismatch for encoder.contextBlock.conv_A2.weight: copying a param with shape torch.Size([1, 3, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 1, 3, 3, 32]).
        size mismatch for encoder.contextBlock.conv_B1.weight: copying a param with shape torch.Size([1, 3, 3, 16, 32]) from checkpoint, the shape in current model is torch.Size([32, 1, 3, 3, 16]).
        size mismatch for encoder.contextBlock.conv_B2.weight: copying a param with shape torch.Size([3, 1, 3, 32, 32]) from checkpoint, the shape in current model is torch.Size([32, 3, 1, 3, 32]).
        size mismatch for encoder.downBlock0.conv_A1.weight: copying a param with shape torch.Size([3, 1, 3, 32, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 1, 3, 32]).
        size mismatch for encoder.downBlock0.conv_A2.weight: copying a param with shape torch.Size([1, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3, 64]).
        size mismatch for encoder.downBlock0.conv_B1.weight: copying a param with shape torch.Size([1, 3, 3, 32, 64]) from checkpoint, the shape in current model is torch.Size([64, 1, 3, 3, 32]).
        size mismatch for encoder.downBlock0.conv_B2.weight: copying a param with shape torch.Size([3, 1, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 1, 3, 64]).
        size mismatch for encoder.downBlock0.pool.weight: copying a param with shape torch.Size([3, 3, 3, 64, 64]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).

Hope someone can help me !!!

**Comment by rmarcuzzi** [comment]
Hi!
I think it's a problem with the version of `spconv`. This is apparently a breaking change introduced in version 2.x as described in their [github](https://github.com/traveller59/spconv/blob/master/docs/SPCONV_2_BREAKING_CHANGEs.md).
In the readme I provided the [link](https://github.com/traveller59/spconv/tree/fad3000249d27ca918f2655ff73c41f39b0f3127) to the repo containing version 1.2.1, with which the code should work!
